// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-rYR2VHxAQEgU4XExdTI7DLGS3smSlb8',
    appId: '1:15819268925:web:1e272f8634e48c02a61b54',
    messagingSenderId: '15819268925',
    projectId: 'weather-app-372be',
    authDomain: 'weather-app-372be.firebaseapp.com',
    storageBucket: 'weather-app-372be.appspot.com',
    measurementId: 'G-2FE27T4RTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfgnAkaRNX7gsGhZrCDZ6w5PY55UX5zwE',
    appId: '1:15819268925:android:ef4155748df79d39a61b54',
    messagingSenderId: '15819268925',
    projectId: 'weather-app-372be',
    storageBucket: 'weather-app-372be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtjfFIz1kan1gLNjdU12ArZpqbeEBTzjQ',
    appId: '1:15819268925:ios:ce95c97c684ac31fa61b54',
    messagingSenderId: '15819268925',
    projectId: 'weather-app-372be',
    storageBucket: 'weather-app-372be.appspot.com',
    iosClientId: '15819268925-2bfej1io0u467skaneb6trc93bvii69r.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtjfFIz1kan1gLNjdU12ArZpqbeEBTzjQ',
    appId: '1:15819268925:ios:ce95c97c684ac31fa61b54',
    messagingSenderId: '15819268925',
    projectId: 'weather-app-372be',
    storageBucket: 'weather-app-372be.appspot.com',
    iosClientId: '15819268925-2bfej1io0u467skaneb6trc93bvii69r.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
